seed: 42
prefer_cuda: true
amp: true
image_size: 256
batch_size: 4
num_workers: 0
epochs: 30
lr: 0.0001
weight_decay: 0.0001
encoder_name: densenet121
encoder_weights: imagenet
train_csv: data/splits/fracatlas/segmentation_train.csv
val_csv: data/splits/fracatlas/segmentation_val.csv
test_csv: data/splits/fracatlas/segmentation_test.csv
run_dir: ml/runs/segmentation_unetpp_densenet121
